backend:
  name: github
  repo: devmecha/Restaurant_Demo
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img/gallery" # Media files will be stored in the repo under images/uploads

collections:
  - name: "food" # Used in routes
    label: "Food Item" # Used in the UI
    folder: "site/content/food" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Name of Item", name: "layout", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "hidden", default: ["lunch","dinner"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of food", name: "type", widget: "string", default: ["Tagine"]}
      - {label: "Price", name: "price", widget: "string"}
  - name: "drinks" # Used in routes
    label: "Drinks Item" # Used in the UI
    folder: "site/content/drinks" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Name of Drink", name: "layout", widget: "string"}
      - {label: "Drink Marker", name: "categories", widget: "hidden", default: ["drinks"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of drinks", name: "type", widget: "string", default: ["Tea", "Juice", "Lemonade"]}
      - {label: "Price", name: "price", widget: "string"}